//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResLabels", typeof(ResLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address .
        /// </summary>
        public static string Address_ {
            get {
                return ResourceManager.GetString("Address ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City .
        /// </summary>
        public static string City_ {
            get {
                return ResourceManager.GetString("City ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country .
        /// </summary>
        public static string Country_ {
            get {
                return ResourceManager.GetString("Country ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email .
        /// </summary>
        public static string Email_ {
            get {
                return ResourceManager.GetString("Email ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email or Password is incorrect.
        /// </summary>
        public static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female .
        /// </summary>
        public static string Female_ {
            get {
                return ResourceManager.GetString("Female ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName .
        /// </summary>
        public static string First_Name_ {
            get {
                return ResourceManager.GetString("First Name ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender .
        /// </summary>
        public static string Gender_ {
            get {
                return ResourceManager.GetString("Gender ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las tName .
        /// </summary>
        public static string LastName_ {
            get {
                return ResourceManager.GetString("LastName ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male .
        /// </summary>
        public static string Male_ {
            get {
                return ResourceManager.GetString("Male ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password .
        /// </summary>
        public static string Password_ {
            get {
                return ResourceManager.GetString("Password ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number .
        /// </summary>
        public static string PhoneNumber_ {
            get {
                return ResourceManager.GetString("PhoneNumber ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username .
        /// </summary>
        public static string Username_ {
            get {
                return ResourceManager.GetString("Username ", resourceCulture);
            }
        }
    }
}
